package com.example.smashlog;

public enum CHARACTER {
    BanjoKazooie(1),
    Bayonetta(2),
    Bowser(3),
    BowserJr(4),
    CaptainFalcon(5),
    Chrom(6),
    Cloud(7),
    Corrin(8),
    Daisy(9),
    DarkPit(10),
    DarkSamus(11),
    Diddy(12),
    DonkeyKong(13),
    DrMario(14),
    DuckHunt(15),
    Falco(16),
    Fox(17),
    Ganondorf(18),
    Greninja(19),
    Hero(20),
    IceClimbers(21),
    Ike(22),
    Incineroar(23),
    Inkling(24),
    Isabelle(25),
    Jigglypuff(26),
    Joker(27),
    Ken(28),
    KingDedede(29),
    KingKRool(30),
    Kirby(31),
    Link(32),
    LittleMac(33),
    Lucario(34),
    Lucas(35),
    Lucina(36),
    Luigi(37),
    Mario(38),
    Marth(39),
    MegaMan(40),
    MetaKnight(41),
    MewTwo(42),
    MrGameAndWatch(43),
    Ness(44),
    Olimar(45),
    PacMan(46),
    Palutena(47),
    Peach(48),
    Pichu(49),
    Pikachu(50),
    PiranhaPlant(51),
    Pit(52),
    PokemonTrainer(53),
    Richter(54),
    Ridley(55),
    ROB(56),
    Robin(57),
    RosalinaAndLuma(58),
    Roy(59),
    Ryu(60),
    Samus(61),
    Sheik(62),
    Shulk(63),
    Simon(64),
    Snake(65),
    Sonic(66),
    Terry(67),
    ToonLink(68),
    Villager(69),
    Wario(70),
    WiiFitTrainer(71),
    Wolf(72),
    Yoshi(73),
    YoungLink(74),
    Zelda(75),
    ZeroSuitSamus(76);

    private final int value;

    CHARACTER(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
