package com.example.smashlog;

public enum CHARACTER {
    BanjoKazooie(0),
    Bayonetta(1),
    Bowser(2),
    BowserJr(3),
    CaptainFalcon(4),
    Charizard(5),
    Chrom(6),
    Cloud(7),
    Corrin(8),
    Daisy(9),
    DarkPit(10),
    DarkSamus(11),
    Diddy(12),
    DonkeyKong(13),
    DrMario(14),
    DuckHunt(15),
    Falco(16),
    Fox(17),
    Ganondorf(18),
    Greninja(19),
    Hero(20),
    IceClimbers(21),
    Ike(22),
    Incineroar(23),
    Inkling(24),
    Isabelle(25),
    Ivysaur(26),
    Jigglypuff(27),
    Joker(28),
    Ken(29),
    KingDedede(30),
    KingKRool(31),
    Kirby(32),
    Link(33),
    LittleMac(34),
    Lucas(35),
    Lucina(36),
    Luigi(37),
    Mario(38),
    Marth(39),
    MegaMan(40),
    MetaKnight(41),
    MewTwo(42),
    MiiBrawler(43),
    MiiSwordfighter(44),
    MiiGunner(45),
    MrGameAndWatch(46),
    Ness(47),
    Olimar(48),
    PacMan(49),
    Palutena(50),
    Peach(51),
    Pichu(52),
    Pikachu(53),
    PiranhaPlant(54),
    Pit(55),
    Richter(56),
    Ridley(57),
    ROB(58),
    Robin(59),
    RosalinaAndLuma(60),
    Roy(61),
    Ryu(62),
    Samus(63),
    Sheik(64),
    Shulk(65),
    Simon(66),
    Snake(67),
    Sonic(68),
    Squirtle(69),
    Terry(70),
    ToonLink(71),
    Villager(72),
    Wario(73),
    WiiFitTrainer(74),
    Wolf(75),
    Yoshi(76),
    YoungLink(77),
    Zelda(78),
    ZeroSuitSamus(79);

    private final int value;

    CHARACTER(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
